title: Team Teach
description: "Social Media for Del Norte High School"
owner_name: Manas Goel
github_username: manas12709
github_repo: "BigIdeaTeamTeach" 
baseurl: "/BigIdeaTeamTeach"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/TeamTeach.md
